
# First issue: no vim motions in `<C-b>[` copy mode
set-window-option -g mode-keys vi

# Second issue: history is by default 2000
set -g history-limit 1000000


# Third issue: copying doesn't go to system clipboard
# note you can still paste with `<C-b>]` but who is going to remember that
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

# Fourth issue: visual mode not supported, only visual line and visual block
# Fifth issue: no text object support (see :h text-objects)
# Sixth issue: no zt or zb
# Seventh issue: no gf or gx
# Eighth issue: no <C-o> or <C-i>
# Nth issue: you will only every be able to get a subset of Vim/Neovim's
# capabilities inside tmux's copy mode

# Ninth issue: splitting windows is different from vim
bind-key v split-window -h
bind-key s split-window -v

# Tenth issue: need to install a plugin here and in vim to synchronize windows
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.config/tmux/plugins/tpm/tpm'
